const jsonCat = [{
        "Hematologia": {
            "Biometria Hematica Completa": "No requiere ayuno.",
            "Plasmodium S.P. (Gota Gruesa)": "No requiere ayuno",
            "Celulas L.E.": "no requiere ayuno",
            "Formula Blanca": "no requiere ayuno",
            "Formula Roja": "no requiere ayuno",
            "Plaquetas": "no requiere ayuno.",
            "Recuento de Reticulocitos": "no requiere ayuno",
            "Velocidad de Sedimentaci\u00f3n Globular (VSG)": "no requiere ayuno"
        },
        "Pruebas de Coagulacion Sanguinea": {
            "Tiempo de Trombina (TT)": "ayuno de 4 hrs",
            "Tiempo de Coagulacion (TC)": "no requiere ayuno",
            "Tiempo de Protombina (TP)": "ayuno de 4 hrs.",
            "Tiempo de Sangrado (TS)": "no requiere ayuno",
            "Tiempo Parcial de Tromboplastina (TPT)": "ayuno de 4 hrs"
        },
        "Pruebas de Funcionamiento Hepatico": {
            "Albumina": "ayuno de 8 hrs",
            "Bilirrubinas": "ayuno de 8 hrs",
            "Fosfatasa Acida Total": "ayuno de 8 hrs",
            "Fosfatasa Acida y Fraccion Prostatica": "ayuno de 4 hrs",
            "Fosfatasa Alcalina": "ayuno de 4 hrs",
            "Gamaglutamiltranspeptidasa (GGT)": "ayuno de 8 hrs",
            "Proteinas Totales": "ayuno de 8 hrs",
            "Proteinas Totales y relacion (A/G)": "ayuno de 8 hrs",
            "TGO - AST": "ayuno de 8 hrs",
            "TGP - ALT": "ayuno de 8 hrs"
        },
        "Enzimas": {
            "Amilasa Serica": "ayuno de 4 hrs",
            "Colinesterasa": "ayuno de 8 hrs",
            "Creatinfosfoquinasa (CPK)": "ayuno de 4 hrs",
            "Creatinina kinasa fracc. (CK-MB)": "ayuno de 8 hrs",
            "Deshidrogenasa Lactica (DHL)": "ayuno de 8 hrs",
            "Lipasa Serica": "ayuno de 8 hrs",
            "Troponina \"T\"": "Ayuno de 8 horas."
        },
        "Serologia": {
            "Prueba Inmunologica de embarazo (PIE SANGRE)": "no requiere ayuno",
            "Anticuerpos Anti-Helicobacter pylori IgG": "ayuno de 8 hrs",
            "Anticuerpos Anti-Helicobacter pylori IgM": "ayuno de 4 hrs",
            "Anticuerpos Covid-19 IgG/IgM": "ayuno de 8 hrs",
            "Antiestreptolisinas (ASO)": "ayuno de 8 hrs",
            "Coombs Directo": "ayuno de 4 hrs",
            "Coombs Indirecto": "ayuno de 4 hrs",
            "Factor Reumatoide": "ayuno de 8 hrs",
            "Grupo Sanguineo y Rh": "sin ayuno ",
            "Influenza A y B": "no ayuno",
            "Proteina \"C\" Reactiva": "ayuno de 8 hrs",
            "Reacciones Febriles (RF)": "ayuno de 8 hrs",
            "Rosa de Bengala (Anticuerpos antibrucela)": "ayuno de 4 hrs",
            "VDRL Cualitativo": "ayuno de 4 hrs",
            "VIH (HIV) Presuntivo": "ayuno de 4 hrs",
            "Anti-CCP Peptido Ciclico Citrulinado": "ayuno de 8 hrs"
        },
        "Hepatitis": {
            "Anticuerpos Anti Hepatitis \"A\" Total": "ayuno de 8 hrs",
            "Anticuerpos Anti-Hepatitis \"C\" (HCVAc)": "ayuno de 8 hrs",
            "Antigeno de Superficie Hepatitis \"B\" (HBsAg)": "ayuno de 8 hrs",
            "Panel de Hepatitis A + B + C": "ayuno de 8 hrs",
            "Panel de Hepatitis B + C y VIH": "ayuno de 8 hrs"
        },
        "Liquidos Corporales": {
            "Ac. Anti Cisticercos en LCR": "no requiere ayuno",
            "Citoquimico de L.C.R": "no requiere ayuno, las que indique el medico.",
            "Citoquimico de liquido de Ascitis (Peritonial)": "no requiere ayuno,las que indique el medico. ",
            "Citoquimico de lLiquido de Dialisis (Citologico)": "no requiere ayuno",
            "Citoquimico de Liquido Pleural": "no requiere ayuno",
            "Citoquimico de Liquido Sinovial (Citologico)": "no requiere ayuno",
            "Espermatobioscopia Directa": "3 - 5 dias abstinencia sexual hacer cita."
        },
        "Inmunoglobulinas": {
            "Inmunoglobulina \"A\"": "ayuno de 8 hrs",
            "Inmunoglobulina \"E\"": "ayuno de 8 hrs",
            "Inmunoglobulina \"G\"": "ayuno de 8 hrs",
            "Inmunoglobulina \"M\"": "ayuno de 8 hrs",
            "Perfil de Inmunoglobulinas (A,E,G,M)": "ayuno de 8 hrs"
        },
        "Quimica Sanguinea": {
            "Acido Urico serico": "ayuno de 8 hrs",
            "Colesterol HDL": "ayuno de 12 hrs",
            "Colesterol Total": "ayuno de 12 hrs",
            "Creatinina Serica": "ayuno de 8 hrs",
            "Curva de Tolerancia a la Glucosa 2 HRS": "ayuno de 8 hrs",
            "Curva de Tolerancia a la Glucosa 3 HRS": "ayuno de 8 hrs",
            "Glucosa": "ayuno de 8 hrs",
            "Glucosa postcarga 50GR": "ayuno de 8 hrs",
            "Glucosa Post-Prandial": "ayuno de 12 hrs",
            "Hemoglobina Glicosilada": "Ayuno de 8 hrs 5ml sangre total EDTA refrigerado",
            "Indice Homa": "ayuno de 8 hrs 2ml suero refrigerado",
            "Insulina Basal": "ayuno de 8 hrs 2.0 mL de suero. Refrigerado.",
            "Lipidos Totales": "ayuno de 8 hrs 2.0 mL de suero. Refrigerado",
            "Trigliceridos": "ayuno de 12 hrs 2.0 mL de suero. Refrigerado",
            "Urea": "ayuno de 8 hrs 2.0 mL de suero. Refrigerado.",
            "Quimica de 3 (Glucosa, Urea, Creatinina)": "ayuno de 8 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 4 (Glucosa, Urea, Creatinina, AC.Urico)": "ayuno de 8 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 5 (Glucosa, Urea, Creatinina, AC.Urico, Colesterol)": "ayuno de 10 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 6 (Glucosa, Urea, Creatinina, AC.Urico, Colesterol, Trigliceridos)": "ayuno de 12 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 8 (Q6 + HDL + Calcio)": "ayuno de 12 hrs",
            "Quimica de 12 (Qs6 + HDL + L.Totales + LDL + Indice A)": "ayuno de 12 hrs",
            "Quimica de 14 (Qs6 + P.Hepatico compl, DHL, Cal)": "ayuno de 12 hrs",
            "Quimica de 16 (Qs4 + P.Lipidos, PFH, GGT, DHL)": "ayuno de 12 hrs",
            "Quimica de 24 Elementos": "ayuno de 12 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 27 Elementos": "ayuno de 12 hrs ",
            "Quimica de 30 Elementos": "ayuno de 12 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 32 Elementos": "ayuno de 12 hrs 4.0 mL de suero. Refrigerado",
            "Quimica de 33 Elementos": "ayuno de 8 hrs ",
            "Quimica de 34 Elementos": "ayuno de 12 hrs ",
            "Quimica de 35 Elementos": "ayuno de 12 hrs ",
            "Quimica de 45 Elementos": "ayuno de 12 hrs "
        },
        "Check Up": {
            "Check Up (BHC + QS24 + EGO)": "ayuno de 12 hrs ",
            "Check Up (BHC + QS27 + EGO)": "ayuno de 12 hrs",
            "Check Up (BHC + QS32 + EGO)": "ayuno de 12 hrs",
            "Check Up (BHC + QS33 + EGO)": "ayuno de 12 hrs 4 mL de Sangre Total EDTA. 4 mL de suero. 20 mL\nde Orina. Refrigerado",
            "Check Up (BHC + QS34 + EGO)": "ayuno de 12 hrs",
            "Check Up (BHC + QS35 + EGO)": "ayuno de 12 hrs",
            "Check Up (BHC + QS45 + EGO)": "ayuno de 12 hrs",
            "Check Up Masculino (BHC + QS24 + EGO + VIH + PSA)": "ayuno de 12 hrs",
            "Check Up Femenino (BHC + QS24 + EGO + VIH)": "ayuno de 12 hrs"
        },
        "Coprologia": {
            "Coproparasitoscopico": "Muestra del tama\u00f1o de una \u201cnuez,\u201d no debe estar contaminada con orina, agua del inodoro o papel higi\u00e9nico. Contenedor de pl\u00e1stico, est\u00e9ril y con\ntapa de rosca",
            "Coproparasitoscopico serie de 3": "muestra tama\u00f1o nuez muestra por frasco",
            "Rotavirus": "muestra tama\u00f1o nuez muestra por frasco",
            "Amiba en fresco": "muestra tama\u00f1o nuez muestra por frasco",
            "Citologia de moco fecal": "muestra tama\u00f1o nuez muestra por frasco",
            "Azucares reductores y PH": "muestra tama\u00f1o nuez muestra por frasco",
            "Sangre oculta en heces/CPS unico": "muestra tama\u00f1o nuez muestra por frasco",
            "Coprologico": "muestra tama\u00f1o nuez muestra por frasco",
            "Adenovirus": "muestra tama\u00f1o nuez muestra por frasco",
            "Clostridium dificile toxina A y B": "muestra tama\u00f1o nuez muestra por frasco"
        },
        "Marcadores Tumorales": {
            "Alfafetoproteina": "Ayuno de 8 hrs. Tubo Tap\u00f3n Dorado\n(Gel Separador), o rojo, 2.0 mL de suero. Refrigerado",
            "Antigeno CA 125": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado, abstinencia sexual por la menos 3 d\u00edas antes de la toma",
            "Antigeno CA 15-3 (MAMA)": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado, abstinencia sexual por la menos 3 d\u00edas antes de la toma",
            "Antigeno CA 19-9 (Pancreas y colon)": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado, abstinencia sexual por la menos 3 d\u00edas antes de la toma",
            "Antigeno carcinoembrionario (CEA)": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado",
            "Antigeno Prostatico Libre": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado, abstinencia sexual por la menos 3 d\u00edas antes de la toma",
            "Antigeno Prostatico Especifico Total (PSA)": "ayuno de 8 hrs, 2.0 mL de suero. Refrigerado, abstinencia sexual por la menos 3 d\u00edas antes de la toma"
        },
        "Hormonas": {
            "Cortisol en Orina 24hrs": "20 mL de orina de 24 horas. Refrigerada, anotar volumen. ",
            "Cuantificacion de hormona (GCH)": "ayuno de 4 hrs",
            "Estradiol": "ayuno de 4 hrs",
            "Estrogenos": "ayuno de 4 hrs",
            "Gonadotrofina cualitativa (Pie. Sangre)": "ayuno de 4 hrs",
            "Hormona estimulante del foliculo FSH": "ayuno de 4 hrs",
            "LH (Hormona luteinizante)": "ayuno de 4 hrs",
            "Perfil de Climaterio (LH, FSH, E2)": "ayuno de 8 hrs",
            "Perfil ginecologico, ovarico, reproduccion (LH, FSH, PROL, PROG, TEST, E2)": "ayuno de 8 hrs",
            "Perfil hormonal masculino 1 (LH, FSH, TEST)": "ayuno de 4 hrs",
            "Perfil hormonal masculino 2 (LH, FSH, TEST, PROL, E2)": "ayuno de 4 hrs",
            "Perfil testicular (LH, FSH, PROL, TEST)": "ayuno de 8 hrs",
            "Progesterona": "ayuno de 8 hrs",
            "Prolactina": "ayuno de 8 hrs",
            "Prolactina serica (3)": "ayuno de 8 hrs",
            "Testosterona Total": "ayuno de 8 hrs",
            "Testosterona Libre": "ayuno de 8 hrs",
            "Dehidroepiandrosterona (DHEA)": "ayuno de 8 hrs, Tiempo de entregra: Microtec 1DH, Labtec 2 DH. ",
            "Perfil Hormonal Femenino (P. Ginecologico 1, TSH, DHEA, Test Libre)": "ayuno de 8 hrs"
        },
        "Urologia": {
            "AC. Urico urinario 24 HRS": "no requiere ayuno",
            "Albumina en orina de 24 HRS": "20 ml de orina de 24 hrs, refrigerada. ",
            "Amilasa urinaria": "20 ml de orina refrigerada. ",
            "Calcio en orina 24 HRS": "20 ml de orina de 24 hrs, refrigerada. ",
            "Creatinina en orina 24 HRS": "no requiere ayuno",
            "Dep. de creatinina (Orina) 24 HRS": "ayuno de 8 hrs",
            "Depuracion de urea en orina de 24 HRS": "2 ml de suero y 20 ml de orina refrigerado. Ayuno de 8 horas. ",
            "Examen general de orina (EGO)": "20 ml de orina refrigerada. ",
            "Microalbuminuria orina al azar": "20 ml de orina refrigerada. ",
            "Microalbuminuria orina de 24 HRS": "20 ml de orina, refrigerada. ",
            "Proteinas totales en orina de 24 HRS": "20 ml de orina, refrigerada. ",
            "Prueba inmunologica de embarazo en orina": "20 ml de orina, refrigerada. "
        },
        "Bacteriologia": {
            "Cultivos y exudados": "sin estar tomando antibioticos",
            "Cultivo de Hongos": "10  a 15 ml, temperatura ambiente, frasco esterl o medio de transporte.",
            "BAAR orina / 2 muestras": "3 a 5 ml de muestra. 2 muestras.",
            "BAAR orina / expectoracion (Serie de 10)": "3 a 5 ml. temp. ambiente. 10 muestras. ",
            "BAAR orina / expectoracion (Serie de 3)": "3 a 5 ml de muestra. 3 muestras. ",
            "BAAR orina / expectoracion (Serie de 5)": "2 a 3 ml de muestra. 5 muestras. ",
            "BAAR orina / expectoracion unica muestra": "3 a 5 m, temp. ambiente, ,uestra de la ma\u00f1ana o flema sin saliva.",
            "Cristalografia en moco cervical": "*",
            "Eosinofilos en moco nasal": "1 Laminilla fijada por fosa nasal.en alcohol, muestra de moco nasal. ",
            "Hemocultivo": "Sangre total  a temp. ambiente. ",
            "Tincion Gram": "Secrecion extendida en laminilla fijada con calor. "
        },
        "Electrolitos": {
            "2 electrolitos": "Muestra de suero. ayuno de 8 hrs",
            "3 electrolitos": "Muestra de suero.ayuno de 8 hrs",
            "4 electrolitos": "Muestra de suero. ayuno de 8 hrs",
            "5 electrolitos": "Muestra de suero. ayuno de 8 hrs",
            "6 electrolitos": "Muestra  de suero, ayuno de 8 hrs",
            "Calcio": "Muestra de suero. Ayuno de 8 hr. ",
            "Cloro": "Muestra de suero. ayuno de 8 hrs",
            "Fosforo": "Muestra de suero, ayuno de 8 horas. ",
            "Magnesio": "Muestra de suero, ayuno de 8 hrs",
            "Potasio": "Muestra de suero. ayuno de 8 hrs",
            "Sodio": "Muestra de suero. ayuno de 8 hrs",
            "Hierro": "Muestra de suero.ayuno de 8 hrs"
        },
        "Drogas de Abuso": {
            "Anfetamina": "20 ml de orina refrigerada.",
            "Benzodiacepinas": "20 ml de orina refrigerada. ",
            "Cocaina": "20 ml de orina, refrigerada. ",
            "Marihuana": "20 ml de orina, refrigerada. ",
            "Metanfetaminas": "20 ml de orina, refrigerada. ",
            "Opiaceos (Morfina, heroina, codeina)": "20 ml de orina refrigerada. ",
            "Antidoping Drogas (3) (COC + THC + ANF)": "20 ml de orina, refrigerada. ",
            "Antidoping de drogas (5) (COC + THC + ANF + BAR + BZO)": "20 ml de orina, refrigerada. ",
            "Antidoping de drogas (5) (COC + THC + ANF + OPI + MET)": "20 ml de orina, refrigerada. "
        },
        "Drogas Terapeuticas": {
            "Acido Valproico (Valproato de mg)": "ayuno de 8 hrs no tomar medicamento el dia que venga",
            "Carbamazepina (Tegretol)": "ayuno de 4 hrs no tomar medicamento el dia que venga",
            "Difenilhidantoina (DFH, fenitoina)": "ayuno de 8 hrs no tomar medicamento el dia que venga ",
            "Digoxina": "ayuno de 8 hrs tomar a la hora indicada por el medico ",
            "Fenobarbital": "ayuno de 8 hrs ",
            "Teofilina (Aminofilina)": "ayuno de 8 hrs  (No ingeriir cafeina 24 hr previo a la toma de muestra)",
            "Clonazepam": "ayuno de 8 hrs",
            "Diazepam": "ayuno de 8 hrs ",
            "Litio": "ayuno de 8 hrs ",
            "Topiramato": "ayuno de 8 hrs ",
            "Oxcarbazepina": "ayuno de 8 hrs ",
            "Lamotrigina": "ayuno de 8 hrs ",
            "Levetiracetam": "ayuno de 8 hrs ",
            "Tacrolimus": "Sangre total no ayuno"
        },
        "Patologia": {
            "Papanicolaou Convencional": "3 dias de abstinencia  sexual, no sangrado sin medicamento",
            "Biopsias (1 muestra) (Hernia)": "no requiere ayuno",
            "Biopsias (2 muestras)": "no requiere ayuno",
            "Biopsias (3 muestras)": "no requiere ayuno",
            "Citologia BAAF (4 laminillas) Biopsia por aspiracion con aguja fina. ": "no requiere ayuno",
            "Papaniculaou en Base Liquida (Monocapa)": "3 dias de abstinencia no sangrado sin medicamento",
            "Piezas Quirurgicas (Hospitales)": "No requiere ayuno, Muestra a analizar. ",
            "Quiste simple de bazo": "no requiere ayuno",
            "Tipificacion por PCR y secuenciacion de virus del papiloma humano en frotis o biopsia": "no requiere ayuno"
        },
        "Perfiles": {
            "Perfil de Lipidos (COL, TRIG, HDL, VLDL, LDL, I.A)": "Ayuno de 8 hrs 4ml suero refrigerado",
            "Perfil Reumatoide (VSG, A. URICO, ASO, PCR, FR)": "Ayuno de 8 hrs 2ml suero refrigerado 4ml sangre total EDTA",
            "Perfil Cardiaco 1 (TGO, TGP, DHL, CK, CKMB)": "Ayuno de 8 hrs 3ml suero refrigerado",
            "Perfil de Hierro con Ferritina": "Ayuno de 8 hrs 3ml suero refrigerado",
            "Perfil de Hierro (Hierro, Fijacion, Libre, Saturacion)": "Ayuno de 8 hrs 2ml suero refrigerado",
            "Perfil Diabetico (BHC, EGO, QS4, P.Lipidos, Hb A1C)": "Ayuno de 12 hrs primer orina de la ma\u00f1ana",
            "Perfil Guarderia (Ex. Faringeo, EGO, CPS 3)": "Primer orina sin aseo bucal no antibiotico 5 dias 3 muestras fecales recientes. ",
            "Perfil Hemorragico (TC, TS, TP, TPT, PLAQUETAS)": "Ayuno de 4 hrs",
            "Perfil preescolar (Ex. faringeo, gpo rh, cps 1)": "ayuno de 8 hrs sin aseo bucal no antibiotico 5 dias",
            "Perfil prenatal (bh, rh, ego, qs3, hiv, vdrl)": "ayuno de 8 hrs y muestra de orina en frasco esteril",
            "Perfil preoperatorio (bh, ego, glucosa, gpo y rh, tp, tpt)": "ayuno de 8 hrs y muestra de orina en frasco esteril",
            "Perfil prostatico (Fraccion prostatica, fosfatasa acida, psa total, psa libre)": "ayuno de 4 hrs",
            "Perfil renal 1 (Urea, crea, ego)": "ayuno de 8 hrs muestra de orina",
            "Perfil renal 2 (Dep. de creat, urea, n. ureico, ego, microalbumina)": "ayuno de 8 hrs y muestra de orina en frasco esteril",
            "Perfil torch completo": "ayuno de 8 hrs",
            "Perfil toxemico (bh, qs4, pfhcompletas, gpo rh, tp-tpt, ego)": "ayuno de 8 hrs orina",
            "PFH 1 (Bil, tgo, tgp)": "ayuno de 8 hrs",
            "PFH 2 (Bil, tgo, tgp, alp, pt, alb, glob, rela a/g)": "ayuno de 8 hrs",
            "Prenupciales por pareja": "ayuno de 4 hrs",
            "Prenupciales individual": "ayuno de 4 hrs",
            "Vigilancia de embarazo (bh, ego, glucosa, urea)": "ayuno de 8 hrs y muestra de orina en frasco esteril",
            "Perfil alergia alimenticia": "ayuno de 8 hrs",
            "Perfil alergia inhalatorio": "ayuno de 8 hrs"
        },
        "Tiroides": {
            "Hormona Estimulante de la Tiroides (TSH)": "ayuno de 8 horas ",
            "Perfil Tiroideo Completo + Ac. Antitiroideos": "ayuno de 8 hrs ",
            "Perfil Tiroideo 1 (t4l, tsh)": "ayuno de 8 hrs ",
            "Perfil Tiroideo 2 (t3, t4, tsh)": "ayuno de 8 hrs ",
            "Perfil Tiroideo 3 (t3, t4, t4l, tsh)": "ayuno de 8 hrs ",
            "Perfil Tiroideo 4": "ayuno de 8 hrs ",
            "Perfil Tiroideo 5 (t3, t3l, t4, tsh, iodo proteico)": "ayuno de 8 hrs",
            "Perfil Tiroideo 6 (t3, t4, t4l, tsh, Iodo)": "ayuno de 8 hrs",
            "Perfil tiroideo 7 Completo": "ayuno de 8 hrs ",
            "T3 Libre (T3L)": "ayuno de 8 hrs ",
            "T3 Total (T3)": "ayuno de 8 hrs ",
            "T4 Libre (T4L)": "ayuno de 8 hrs ",
            "T4 Total (T4)": "ayuno de 8 hrs ",
            "TU (Captacion de Triyodotironina)": "ayuno de 8 hrs "
        },
        "Enfermedades de Transmision Sexual": {
            "Paquete Basico ETS 1 Mujer (Anticuerpos VIH, V.D.R.L)": "ayuno de 8 hrs",
            "Paquete Basico ETS 2 Mujer (Ac. VIH, V.D.R.L, Chlamydia Cervical Antigeno, Cultivo de Mycoplasma y Ureaplasma)": "ayuno de 8 hrs no antibioticos no relaciones sexuales 2ml suero refrigerado, no haber orinado",
            "Paquete Basico ETS 1 Hombre (Ac. VIH, V.D.R.L)": "ayuno de 4 hrs",
            "Paquete Basico ETS 2 Hombre (Anticuerpos VIH, V.D.R.L, Chlamydia Uretral Antigeno, Cultivo Uretral)": "ayuno de 8 hrs no antibiotico no relaciones sexuales 2ml suero refrigerado 5ml semen refrigerado"
        }
    }
]